# Generated by Django 4.2.2 on 2023-10-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCentre', '0002_remove_prescription_noofdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='NoOfDays',
            field=models.CharField(db_column='noofdays', default=0, max_length=10),
            preserve_default=False,
        ),
    ]
